### PR TITLE
updated styles on buttons

### PR DESCRIPTION
**Pull request by crabcatcher0**
I’ve incorporated the suggested changes and am looking forward to your review. Thank you once again for your guidance.

This is a continuation from https://github.com/lunaflight/courserekt/pull/39.

### CODE REVIEW

**Comment by lunaflight** [comment]
hey, i've tested your changes and noted the following

before:
image

after:
image

concretely, this is the extra padding that is added on the bottom:
image

could you elaborate on the rationale of adding extra padding on the bottom? i think that detail has been left out in your PR description - it's not very obvious

**Comment by crabcatcher0** [comment]
before:
gg

As you can see there is no space at the button for future buttons so after adding it would be sure to have space on the bottom for other future buttons too. Moreover, i would like to propose that if we could have these buttons dynamic. So, that for every year we just add years and the buttons would be for that respective year.

**Comment by lunaflight** [comment]
I'm happy if you open an issue about your proposal!

As for the button stacking, that seems like a concern that is easily fixed by merging, so I have no problems with that. As more years are added, row wrapping is definitely something that we want look good. I want to ensure that your fix is reflected properly, so I want to get this right.
I'm unable to reproduce such a view though with multiple browsers - I can only see the buttons laid out horizontally.
Could you try pressing `Ctrl + F5` in https://courserekt.vercel.app to do a hard refresh and see if the buttons are still laid out like that with `24/25` under `21/22`?
If it is still laid out like that, could you tell me what browser you're using?

**Comment by crabcatcher0** [comment]
@lunaflight  for me even after hard reset it's same might be because of my screen width but i tried on my other device it shows horizontally. so for medium screen it might be the issues and thanks again.
I will be opening new PR for my proposal.

**Comment by SpookyYomo** [comment]
> before: gg
> 
> As you can see there is no space at the bottom for future buttons so after adding it would be sure to have space on the bottom for other future buttons too. Moreover, i would like to propose that if we could have these buttons dynamic. So, that for every year we just add years and the buttons would be for that respective year.

@crabcatcher0 Resizing my browser and loading the webpage on a mobile phone in portrait did not get my the web to stack the buttons (even with forced refresh), how exactly did you create the stack? We're very curious to replicate. (Device type and browser used, maybe even user-agent string and browser window size: Consider https://browserleaks.com/javascript to get the windows sizes for us too!) Thanks :D

**Comment by crabcatcher0** [comment]
I am using Ubuntu
Browser Information:
Browser: Google Chrome (Version 128.0.6613.84)
User-Agent String: Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/128.0.0.0 Safari/537.36
Screen Information:
Viewport Size: 1285×615 pixels

**Pull request closed without merging**
